### ISSUE TITLE
api endpoint tests

### ISSUE THREAD

**Issue by barni363hun** [barni363hun/Stabox#32]
- auth0 
    - login
    - registration
- user
    - create
    - update
    - delete
    - getAllUsername
    - getMyData
    - getAllUser - admin
- transaction
    - getMyTransactions
    - getAllTransactions
    - buyStabucks
- exchangeDate
    - create
    - delete
    - getMyExchangeDates
    - update
- shipper
    - create
    - modify
    - delete
    - getMyShipperInfo
    - acceptPackage
    - getActivePackages
    - selectPostDate
    - addShippingDate
- vehicle
    - create
    - delete
    - getMyVehicles
- address
    - create
    - delete
    - getMyAddresses
- package
    - create
    - getAllPackage
    - delete
    - sent

**Comment by CserpakRobert** [comment]
deprecated
